import {test,expect} from '@playwright/test';
const base='https://collections.test';
async function fixture(page,{collection=true,count=3,ratings=true,partial=false,delay=0}={}) {
 const calls=[];let failCollection=false;
 await page.addInitScript(({base,ratings})=>{
  if(!localStorage.getItem('nuvio-fork.webos.v1'))localStorage.setItem('nuvio-fork.webos.v1',JSON.stringify({guestMode:true,addons:[{url:base+'/manifest.json',manifest:{id:'fixture',name:'Fixture',resources:['catalog','meta'],types:['movie'],idPrefixes:['tt'],catalogs:[{id:'popular',name:'Filmes',type:'movie'}]}}],settings:{},progress:{},watched:{},library:{}}));
  if(!localStorage.getItem('nuvio-fork.webos.metadata.v1'))localStorage.setItem('nuvio-fork.webos.metadata.v1',JSON.stringify({key:'a'.repeat(32),language:'pt-BR'}));
  if(ratings && !localStorage.getItem('nuvio-fork.webos.ratings.v1'))localStorage.setItem('nuvio-fork.webos.ratings.v1',JSON.stringify({key:'fixture-key-123',enabled:true,providers:['imdb','tmdb','tomatoes','letterboxd']}));
 },{base,ratings});
 const movie={id:'tt100',type:'movie',name:'Saga de teste',poster:base+'/image.svg',background:base+'/image.svg',description:'A história continua.',imdbRating:'7.5',cast:['Pessoa']};
 await page.route(base+'/**',route=>{const url=route.request().url();if(url.endsWith('.svg'))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="780" height="440"><rect width="780" height="440" fill="#2a3944"/></svg>'});calls.push({url});return route.fulfill({json:url.includes('/catalog/')?{metas:[movie]}:{meta:{...movie,id:url.includes('/tt101')?'tt101':'tt100',name:url.includes('/tt101')?'Filme da coleção':'Saga de teste'}}});});
 await page.route('https://api.themoviedb.org/**',async route=>{
  const url=route.request().url();calls.push({url});let data;
  if(url.includes('/collection/')){if(failCollection)return route.fulfill({status:503,json:{}});data={id:9,name:'A saga completa',parts:Array.from({length:count},(_,i)=>({id:101+i,title:`Filme ${i+1}`,release_date:`${2000+i}-01-01`,poster_path:'/image.svg',backdrop_path:'/image.svg'})).reverse()};}
  else if(url.includes('/find/'))data={movie_results:[{id:url.includes('tt101')?101:100}]};
  else {const id=Number(new URL(url).pathname.split('/').pop());data={id,title:'Saga de teste',imdb_id:id===101?'tt101':'tt100',vote_average:8.4,vote_count:200,belongs_to_collection:collection?{id:9,name:'A saga completa'}:null,credits:{cast:[]},recommendations:{results:[]}};}
  return route.fulfill({json:data});
 });
 await page.route('https://image.tmdb.org/**',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="780" height="440"><rect width="780" height="440" fill="#263e4e"/><path d="M0 440L300 80L500 340L780 140V440" fill="#416776"/></svg>'}));
 await page.route('https://api.mdblist.com/**',async route=>{const request=route.request(),url=request.url(),provider=new URL(url).pathname.split('/').pop();calls.push({url,method:request.method(),body:request.postDataJSON(),headers:request.headers()});if(delay)await new Promise(r=>setTimeout(r,delay));return route.fulfill(partial && provider==='tomatoes'?{status:429,json:{}}:{json:{ratings:[{rating:{imdb:8.2,tmdb:8.4,tomatoes:93,letterboxd:4.1}[provider] ?? null}]}}).catch(()=>{});});
 return {calls,fail:()=>failCollection=true};
}
async function detail(page){await page.goto('/');await page.locator('.home-rows .card').first().click();await expect(page.locator('.detail-title')).toBeVisible();}
async function settings(page){await page.goto('/');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Ajustes',exact:true}).click();await page.getByRole('button',{name:'Integrações',exact:true}).click();await page.getByRole('button',{name:/Avaliações MDBList/}).click();}
test('franchise is ordered by release, uses fork geometry and restores its selected movie after details',async({page})=>{
 const f=await fixture(page);await detail(page);await expect(page.locator('.collection-rail .card')).toHaveCount(3);await expect(page.locator('.collection-rail .card').first()).toHaveAttribute('aria-label','Filme 1');const box=await page.locator('.collection-rail .art').first().boundingBox();expect(box.width).toBe(520);expect(box.height).toBe(292);await page.locator('.collection-rail .card').first().click();await expect(page.locator('.detail-title')).toContainText('Filme da coleção');expect(f.calls.some(x=>x.url.includes('/meta/movie/tt101.json'))).toBe(true);await page.keyboard.press('Escape');await expect(page.locator('.collection-rail .card').first()).toBeFocused();await page.screenshot({path:'test-results/collection-1920.png'});
});
test('large franchises show 30 cards per page and refresh failure preserves the usable page',async({page})=>{
 const f=await fixture(page,{count:65});await detail(page);await expect(page.locator('.collection-rail .card')).toHaveCount(30);await page.locator('.movie-collection').getByRole('button',{name:'Próximos',exact:true}).click();await expect(page.locator('.collection-rail .card').first()).toHaveAttribute('aria-label','Filme 31');f.fail();await page.getByRole('button',{name:'Atualizar coleção',exact:true}).click();await expect(page.locator('.movie-collection')).toContainText('Coleção anterior preservada');await expect(page.locator('.collection-rail .card')).toHaveCount(30);
});
test('no membership does not invent a collection; direct TMDB rating never replaces IMDb attribution',async({page})=>{
 const f=await fixture(page,{collection:false,ratings:false});await detail(page);await expect(page.getByRole('button',{name:'TMDB: 84',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'IMDb: 7,5',exact:true})).toBeVisible();await expect(page.locator('.movie-collection')).toBeHidden();expect(f.calls.some(x=>x.url.includes('/collection/'))).toBe(false);expect(f.calls.some(x=>x.url.includes('api.mdblist'))).toBe(false);
});
test('partial ratings preserve other sources and use only read lookups without Nuvio credentials',async({page})=>{
 const f=await fixture(page,{partial:true});await detail(page);await expect(page.locator('.rating-item')).toHaveCount(3);await expect(page.getByRole('button',{name:'IMDb: 8,2',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Avaliações indisponíveis',exact:true})).toBeVisible();const calls=f.calls.filter(x=>x.url.includes('api.mdblist'));expect(calls).toHaveLength(4);for(const call of calls){expect(call.method).toBe('POST');expect(call.body).toEqual({ids:['tt100'],provider:'imdb'});expect(call.headers.authorization).toBeUndefined();expect(call.url).toContain('/rating/movie/');}await page.getByRole('button',{name:'Letterboxd: 4,1',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Fonte: MDBList');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Letterboxd: 4,1',exact:true})).toBeFocused();await page.screenshot({path:'test-results/ratings-1920.png'});
});
test('MDBList provider preferences persist separately and removal stops lookups',async({page})=>{
 const f=await fixture(page);await settings(page);await page.getByRole('checkbox',{name:'Letterboxd',exact:true}).uncheck();await page.getByRole('button',{name:'Salvar',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('nuvio-fork.webos.v1').includes('fixture-key-123'))).toBe(false);await detail(page);await expect(page.locator('.detail-ratings')).toHaveAttribute('aria-busy','false');expect(f.calls.some(x=>x.url.includes('/rating/movie/letterboxd'))).toBe(false);await settings(page);await expect(page.locator('input[type=password]')).toHaveValue('');await page.getByRole('button',{name:'Remover chave',exact:true}).click();const before=f.calls.filter(x=>x.url.includes('api.mdblist')).length;await detail(page);await expect(page.getByRole('button',{name:'TMDB: 84',exact:true})).toBeVisible();expect(f.calls.filter(x=>x.url.includes('api.mdblist'))).toHaveLength(before);
});
test('leaving detail cancels late rating results without changing history or rebuilding the old screen',async({page})=>{
 const f=await fixture(page,{delay:700});await detail(page);await expect.poll(()=>f.calls.filter(x=>x.url.includes('api.mdblist')).length).toBe(3);await page.keyboard.press('Escape');await expect(page.locator('.home-rows')).toBeVisible();await expect(page.locator('.detail-ratings')).toHaveCount(0);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nuvio-fork.webos.v1')).progress)).toEqual({});
});
