import {test,expect} from '@playwright/test';
const base='https://metadata.test',key='a'.repeat(32);
async function fixture(page,{configured=true,fail=false,delay=0,bridge=false}={}) {
 const calls=[];
 await page.addInitScript(({base,key,configured,bridge})=>{
  localStorage.setItem('nuvio-fork.webos.v1',JSON.stringify({guestMode:true,addons:[{url:base+'/manifest.json',manifest:{id:'metadata',name:'Fixture',resources:['catalog','meta','stream'],types:['movie','series'],idPrefixes:['tt'],catalogs:[{id:'popular',name:'Filmes',type:'movie'}]}}],progress:{},library:{},watched:{},settings:{}}));
  if(configured)localStorage.setItem('nuvio-fork.webos.metadata.v1',JSON.stringify({key,language:'pt-BR'}));
  if(bridge)window.PalmServiceBridge=class{call(uri,params){window.lastLaunch={uri,params:JSON.parse(params)};queueMicrotask(()=>this.onservicecallback('{"returnValue":true}'));}cancel(){}};
 },{base,key,configured,bridge});
 const meta={id:'tt100',type:'movie',name:'Título de referência',description:'Sinopse do catálogo.',poster:base+'/photo.svg',background:base+'/photo.svg',app_extras:{cast:[{name:'Atriz de teste',tmdbId:7,character:'Personagem',photo:base+'/photo.svg'}],directors:[{name:'Diretor de teste',tmdbId:8,photo:base+'/photo.svg'}]},trailers:[{source:'abcdefghijk',name:'Trailer do addon'}]};
 await page.route(base+'/**',route=>{const u=route.request().url();calls.push(u);return route.fulfill({json:u.includes('/catalog/')?{metas:[meta]}:u.includes('/meta/movie/tt101')?{meta:{id:'tt101',type:'movie',name:'Filme recomendado',description:'Detalhes do addon'}}:{meta}});});
 await page.route('https://api.themoviedb.org/**',async route=>{
  const u=new URL(route.request().url());calls.push(u.pathname);if(delay)await new Promise(r=>setTimeout(r,delay));if(fail)return route.fulfill({status:503,json:{}}).catch(()=>{});
  let data;
  if(u.pathname.includes('/find/'))data={movie_results:[{id:100}]};
  else if(u.pathname.includes('/person/'))data={id:u.pathname.endsWith('/8')?8:7,name:'Pessoa de teste',profile_path:'/photo.jpg',biography:'Biografia completa. '.repeat(100),birthday:'1980-01-01',known_for_department:'Acting',combined_credits:{cast:Array.from({length:45},(_,i)=>({id:101+i,title:'Crédito '+i,media_type:i%2?'tv':'movie',poster_path:'/photo.jpg',release_date:`${2025-i}-01-01`}))}};
  else if(u.pathname.endsWith('/configuration'))data={images:{}};
  else {const id=Number(u.pathname.split('/').pop());data={id,title:id===100?'Título TMDB':'Filme recomendado',imdb_id:id===100?'tt100':'tt101',credits:{cast:[{id:7,name:'Atriz de teste',character:'Personagem TMDB',profile_path:'/photo.jpg'}]},videos:{results:[{site:'YouTube',key:'12345678901',name:'Trailer TMDB',type:'Trailer',iso_639_1:'pt'}]},recommendations:{results:[{id:101,title:'Filme recomendado',poster_path:'/photo.jpg'}]}};}
  return route.fulfill({json:data}).catch(()=>{});
 });
 await page.route(/https:\/\/(image.tmdb.org|img.youtube.com)\//,route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="320" height="480"><rect width="320" height="480" fill="#30424b"/><circle cx="160" cy="140" r="80" fill="#87969b"/><path d="M0 480V300L160 200L320 300V480" fill="#52676e"/></svg>'}));
 return {calls};
}
async function detail(page){await page.goto('/');await page.locator('.home-rows .card').first().click();await expect(page.locator('.detail-title')).toBeVisible();}
test('addon cast and trailers work without TMDB credentials, with honest setup for filmography',async({page})=>{
 const f=await fixture(page,{configured:false});await detail(page);await expect(page.locator('.cast-card')).toHaveCount(2);await expect(page.locator('.cast-card').first()).toContainText('Diretor de teste');await page.locator('.cast-card').nth(1).click();await expect(page.locator('.person-hero')).toContainText('Atriz de teste');await expect(page.getByRole('button',{name:'Configurar TMDB',exact:true})).toBeVisible();expect(f.calls.some(x=>x.startsWith('/3/'))).toBe(false);await page.keyboard.press('Escape');await expect(page.locator('.cast-card').nth(1)).toBeFocused();
 await page.getByRole('tab',{name:'Trailers',exact:true}).click();await expect(page.locator('.trailer-card')).toHaveCount(1);
});
test('TMDB person shows bounded filmography and biography; detail return preserves poster and cast focus',async({page})=>{
 await fixture(page);await detail(page);await expect(page.locator('.metadata-source')).not.toContainText('Carregando');await page.locator('.cast-card').filter({hasText:'Atriz de teste'}).click();await expect(page.locator('.filmography .card')).toHaveCount(30);const portraitBox=await page.locator('.person-photo').boundingBox();expect(portraitBox.width).toBe(320);expect(portraitBox.height).toBe(480);const poster=page.locator('.filmography .card').first();await poster.click();await expect(page.locator('.detail-title')).toContainText('Filme recomendado');await page.keyboard.press('Escape');await expect(poster).toBeFocused();await page.getByRole('button',{name:'Próximos',exact:true}).click();await expect(page.locator('.filmography .card')).toHaveCount(15);await page.getByRole('button',{name:'Ler biografia de Pessoa de teste'}).click();await expect(page.getByRole('dialog')).toContainText('Biografia completa');await page.keyboard.press('Escape');await page.screenshot({path:'test-results/person-1920.png'});await page.keyboard.press('Escape');await expect(page.locator('.cast-card').filter({hasText:'Atriz de teste'})).toBeFocused();
});
test('recommendations resolve TMDB to IMDb before asking installed addons for details and streams',async({page})=>{
 const f=await fixture(page);await detail(page);await page.getByRole('tab',{name:'Semelhantes'}).click();await expect(page.locator('.related-rail .card')).toHaveCount(1);const artBox=await page.locator('.related-rail .art').boundingBox();expect(artBox.width).toBe(520);expect(artBox.height).toBe(292);await page.locator('.related-rail .card').click();await expect(page.locator('.detail-title')).toContainText('Filme recomendado');expect(f.calls.some(x=>x.includes('/meta/movie/tt101.json'))).toBe(true);await page.keyboard.press('Escape');await expect(page.locator('.related-rail .card')).toBeFocused();await page.screenshot({path:'test-results/detail-related-1920.png'});
});
test('trailer launch uses native YouTube, keeps focus on Back and never writes watch history',async({page})=>{
 await fixture(page,{bridge:true});await detail(page);await page.getByRole('tab',{name:'Trailers',exact:true}).click();await expect(page.locator('.trailer-card')).toHaveCount(2);await page.locator('.trailer-card').first().click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Abrir no YouTube',exact:true}).click();await expect(page.getByRole('dialog').getByRole('status')).toContainText('enviado');expect(await page.evaluate(()=>window.lastLaunch.params.id)).toBe('youtube.leanback.v4');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nuvio-fork.webos.v1')).progress)).toEqual({});await page.screenshot({path:'test-results/trailer-1920.png'});await page.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{keyCode:461,bubbles:true})));await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.trailer-card').first()).toBeFocused();
});
test('TMDB outage preserves addon detail and offers retry; leaving cancels late metadata UI',async({page})=>{
 await fixture(page,{fail:true,delay:200});await detail(page);await expect(page.locator('.detail-title')).toContainText('Título de referência');await expect(page.locator('.metadata-source')).toContainText('indisponível');await expect(page.locator('.cast-card')).toHaveCount(2);await expect(page.getByRole('button',{name:'Tentar novamente',exact:true})).toBeVisible();await page.getByRole('button',{name:'Tentar novamente',exact:true}).click();await page.keyboard.press('Escape');await expect(page.locator('.home-rows')).toBeVisible();await expect(page.locator('.detail-extras')).toHaveCount(0);
});
test('TMDB configuration stores key separately, masks it and removes it without changing Nuvio state',async({page})=>{
 await fixture(page,{configured:false});await detail(page);await page.getByRole('button',{name:'Configurar TMDB',exact:true}).click();await page.getByRole('textbox',{name:'Chave de API TMDB'}).fill(key);await page.getByRole('button',{name:'Salvar e verificar'}).click();await expect(page.getByRole('status').filter({hasText:'TMDB conectado'})).toBeVisible();await expect(page.locator('input[type=password]')).toHaveValue('');expect(await page.evaluate(()=>localStorage.getItem('nuvio-fork.webos.v1').includes('aaaaaaaa'))).toBe(false);await page.getByRole('button',{name:'Remover chave'}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nuvio-fork.webos.metadata.v1')).key)).toBe('');
});

test('removing TMDB credentials cancels an in-flight validation',async({page})=>{
 await fixture(page,{configured:false,delay:600});await detail(page);await page.getByRole('button',{name:'Configurar TMDB',exact:true}).click();await page.getByRole('textbox',{name:'Chave de API TMDB'}).fill(key);await page.getByRole('button',{name:'Salvar e verificar'}).click();await expect(page.getByRole('status').filter({hasText:'Verificando'})).toBeVisible();await page.getByRole('button',{name:'Remover chave'}).click();await expect(page.getByRole('status').filter({hasText:'TMDB desativado'})).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('nuvio-fork.webos.metadata.v1')).key)).toBe('');
});
